print("----->Operators<-----")
print("\n")

print("Arithmetic operators")
print("Assignment operators")
print("Comparison operators")
print("Logical operators")
print("Identity operators")
print("Membership operators")
print("Bitwise operators")
print("\n")

print("Arithmetic operators:")
print("+(Addition) x+y:")
print("-(Subtraction) x-y:")
print("*(Multiplication) x*y:")
print("/(Division) x/y:")
print("%(Modulus) x%y:")
print("**(Exponentiation) x**y:")
print("//(Floor division) x//y:")
print("\n")

print("Assignment operators:")
print("'=' x=5:")
print("'+='  x=x+3:")
print("'-='  x=x-3:")
print("'*='  x=x*3:")
print("'/='  x=x/3:")
print("'%='  x=x%3:")
print("'//=' x=x//3:")
print("'**=' x=x**3:")
print("'&='  x=x&3:")
print("'|='  x=x|3:")
print("'^='  x=x^3:")
print("'>>='  x=x>>3:")
print("'<<='  x=x<<3:")
print("':='  x=3 print(x):")
print("\n")

print("Comparison operators:")
print("'==' (Equal)  x==y")
print("'!=' (Not Equal)  x!=y")
print("'>' (Greater Than)  x>y")
print("'<' (Less Than)  x<y")
print("'>=' (Greater Than or Equal to)  x>=y")
print("'<=' (Less Than or Equal to)  x<=y")
print("\n")

print("Logical operators:")
print("'and' (both statement true)  x<5 and x<10")
print("'or' (one statement true)  x<5 or x<4")
print("'not' (return false if the result is true)  not(x<5 and x <10)")
print("\n")

print("Identity operators:")
print("'is' (both variable are the same)  x is y")
print("'is not' (both variable are not same object)  x is not y")
print("\n")


print("Membership operators:")
print("'in' (sequence with specified value is present in the object)  x in y")
print("'not in' (sequence with specified value is present in the object)  x not in y")
print("\n")


print("Bitwise operators:")
print("'&' (AND)  x&y")
print("'|' (OR)  x|y")
print("'^' (XOR)  x^y")
print("'~' (NOT)  ~x")
print("'<<' (Zero fill left Shift)  x<<y")
print("'>>' (Signed Right Shift)  x>>y")
print("\n")

print("Operator Precedence:")
print("(6 + 3) - (6 + 3):",(6 + 3) - (6 + 3))
print("100 + 5 * 3:",100 + 5 * 3)

print("Operator Precedence:")
print("()	Parentheses")
print("**	Exponentiation")
print("+x  -x  ~x	Unary plus, unary minus, and bitwise NOT")
print("*  /  //  %	Multiplication, division, floor division, and modulus")
print("+  -	Addition and subtraction")
print("<<  >>	Bitwise left and right shifts")
print("&	Bitwise AND")
print("^	Bitwise XOR")
print("|	Bitwise OR")
print("==  !=  >  >=  <  <=  is  is not  in  not in 	Comparisons, identity, and membership operators")
print("not	Logical NOT")
print("and	AND")
print("or	OR")

